### ISSUE TITLE
Crashes after repeated devicelist requests

### ISSUE THREAD

**Issue by trumpton** [trumpton/ChromecastManager#16]
10:47:40 chromecast (592591) notice:Received request: /devicelist from 127.0.0.1:1433205248 - returning device list
10:47:40 chromecast (592591) debug:HTTP session 1 connection closed (127.0.0.1:1433205248)
10:47:41 chromecast (592591) debug:HTTP session 1 connection established from 127.0.0.1:1433205248
10:47:41 chromecast (592591) debug:Friendly name for request: unknown device

10:47:41 chromecast (592591) notice:Received request: /devicelist from 127.0.0.1:1433205248 - returning device list
10:47:41 chromecast (592591) debug:HTTP session 1 connection closed (127.0.0.1:1433205248)
10:47:41 chromecast (592591) debug:RECV: {"version":0,"sender":"Tr@n$p0rt-0","receiver":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","datatype":0,"message":"{\"type\":\"PING\"}"} from 192.168.1.104:8009
10:47:41 chromecast (592591) debug:SEND: {"version":0,"sender":"Tr@n$p0rt-0","receiver":"Tr@n$p0rt-0","namespace":"urn:x-cast:com.google.cast.tp.heartbeat","datatype":0,"message":"{\"type\":\"PONG\"}"} to 192.168.1.104:8009
10:47:41 chromecast (592591) notice:Chromecast 6 at 192.168.1.104:8009 - connection closed by peer
10:47:42 chromecast (592591) debug:HTTP session 1 connection established from 127.0.0.1:1433119152
10:47:42 chromecast (592591) debug:Friendly name for request: unknown device

Program received signal SIGSEGV, Segmentation fault.
0x000055555555e86a in ccgetwatchvarnameat (cch=0x0, index=0) at chromecast_interface.c:494
494	  DATAOBJECT *node = dochild(donoden(cch->vars, index)) ;
(gdb) bt
#0  0x000055555555e86a in ccgetwatchvarnameat (cch=0x0, index=0) at chromecast_interface.c:494
#1  0x000055555555bc1a in chromecast_device_request_process_devicelist (httpsh=0x5555556ba9b0, cclist=0x555555637930, maxcc=128)
    at chromecastmanager_devicerequest.c:290
#2  0x000055555555b32a in chromecast_device_request_process (httpsh=0x5555556ba9b0, cclist=0x555555637930, maxcc=128)
    at chromecastmanager_devicerequest.c:119
#3  0x0000555555557ef0 in main (argc=3, argv=0x7fffffffe048) at chromecastmanager.c:382

**Comment by trumpton** [comment]
Actually the crash is happening after a connection has been dropped with a chromecast device and devicelist tries to get info from it.
Replicate by:
Start program
Unplug a device
Wait 480 seconds
request /devicelist

**Comment by trumpton** [comment]
Update 96cc690 adds check for NULL, which fixes crash.  
Once device disconnected, there is still an attempt to access old handle, causing sigpipe.
Original problem solved.

14:20:43 chromecast (599587) notice:Chromecast device Downstairs Speakers found at 192.168.1.103:32076
14:28:44 chromecast (599587) notice:Disconnecting non-responsive Chromecast 4 at 192.168.1.103:8009
14:28:44 chromecast (599587) notice:Disconnecting non-responsive Chromecast 6 at 192.168.1.103:32108
14:28:44 chromecast (599587) notice:Disconnecting non-responsive Chromecast 8 at 192.168.1.103:32076
14:29:42 chromecast (599587) notice:sigpipe received - ignoring
14:30:16 chromecast (599587) notice:sigpipe received - ignoring
14:30:50 chromecast (599587) notice:sigpipe received - ignoring
14:31:23 chromecast (599587) notice:sigpipe received - ignoring
14:31:57 chromecast (599587) notice:sigpipe received - ignoring
14:32:31 chromecast (599587) notice:sigpipe received - ignoring
14:33:08 chromecast (599587) notice:sigpipe received - ignoring
14:33:42 chromecast (599587) notice:sigpipe received - ignoring
